
namespace GenerateTree.Classes
{
    public static class GenerateData
    {
        public static List<BaseModel> Generate()
        {
            return new List<BaseModel>
            {
                new BaseModel{ Id = 1, Name = "کامپیوتر رومیزی" , ParentCategoryId = 0},
                new BaseModel{ Id = 2, Name = "Desktops" , ParentCategoryId = 1},
                new BaseModel{ Id = 3, Name = "Notebooks" , ParentCategoryId = 1},
                new BaseModel{ Id = 4, Name = "Software" , ParentCategoryId = 1},
                new BaseModel{ Id = 5, Name = "Electronics" , ParentCategoryId = 0},
                new BaseModel{ Id = 6, Name = "Camera & photo" , ParentCategoryId = 5},
                new BaseModel{ Id = 7, Name = "Cell phones" , ParentCategoryId = 5},
                new BaseModel{ Id = 8, Name = "Others" , ParentCategoryId = 5},
                new BaseModel{ Id = 9, Name = "Apparel" , ParentCategoryId = 0},
                new BaseModel{ Id = 10, Name = "Shoes" , ParentCategoryId = 9},
                new BaseModel{ Id = 11, Name = "Clothing" , ParentCategoryId = 9},
                new BaseModel{ Id = 12, Name = "Accessories" , ParentCategoryId = 9},
                new BaseModel{ Id = 13, Name = "Digital downloads" , ParentCategoryId = 0},
                new BaseModel{ Id = 14, Name = "Books" , ParentCategoryId = 0},
                new BaseModel{ Id = 15, Name = "Jewelry" , ParentCategoryId = 0},
                new BaseModel{ Id = 16, Name = "Gift Cards" , ParentCategoryId = 0},
                new BaseModel{ Id = 17, Name = "دوربین عکاسی" , ParentCategoryId = 0},
                new BaseModel{ Id = 18, Name = "هدفون" , ParentCategoryId = 0},
                new BaseModel{ Id = 19, Name = "تبلت" , ParentCategoryId = 0},
                new BaseModel{ Id = 20, Name = "پرینتر" , ParentCategoryId = 0},
                new BaseModel{ Id = 21, Name = "گوشی موبایل" , ParentCategoryId = 45},
                new BaseModel{ Id = 22, Name = "گوشی موبایل سامسونگ" , ParentCategoryId = 21},
                new BaseModel{ Id = 23, Name = "گوشی موبایل نوکیا" , ParentCategoryId = 21},
                new BaseModel{ Id = 24, Name = "گوشی موبایل شیائومی" , ParentCategoryId = 21},
                new BaseModel{ Id = 25, Name = "گوشی موبایل اپل" , ParentCategoryId = 21},
                new BaseModel{ Id = 26, Name = "تبلت" , ParentCategoryId = 0},
                new BaseModel{ Id = 27, Name = "گوشی موبایل آنر" , ParentCategoryId = 21},
                new BaseModel{ Id = 28, Name = "سامسونگ" , ParentCategoryId = 19},
                new BaseModel{ Id = 29, Name = "لنوو" , ParentCategoryId = 19},
                new BaseModel{ Id = 30, Name = "اتاچ" , ParentCategoryId = 19},
                new BaseModel{ Id = 31, Name = "آلکاتل" , ParentCategoryId = 19},
                new BaseModel{ Id = 32, Name = "هارد دیسک" , ParentCategoryId = 0},
                new BaseModel{ Id = 33, Name = "هارد دیسک اینترنال" , ParentCategoryId = 32},
                new BaseModel{ Id = 34, Name = "هارد دیسک اکسترنال" , ParentCategoryId = 32},
                new BaseModel{ Id = 35, Name = "سیگیت" , ParentCategoryId = 33},
                new BaseModel{ Id = 36, Name = "وسترن دیجیتال" , ParentCategoryId = 33},
                new BaseModel{ Id = 37, Name = "سیگیت" , ParentCategoryId = 34},
                new BaseModel{ Id = 38, Name = "وسترن دیجیتال" , ParentCategoryId = 34},
                new BaseModel{ Id = 39, Name = "وسترن دیجیتال" , ParentCategoryId = 34},
                new BaseModel{ Id = 40, Name = "حافظه SSD" , ParentCategoryId = 32},
                new BaseModel{ Id = 41, Name = "لوازم جانبی گوشی و تبلت" , ParentCategoryId = 45},
                new BaseModel{ Id = 42, Name = "کامپیوتر و تجهیزات جانبی" , ParentCategoryId = 45},
                new BaseModel{ Id = 43, Name = "لپ تاپ" , ParentCategoryId = 0},
                new BaseModel{ Id = 44, Name = "کنسول بازی" , ParentCategoryId = 0},
                new BaseModel{ Id = 45, Name = "کالاهای دیجیتال" , ParentCategoryId = 0},
                new BaseModel{ Id = 46, Name = "مانیتور" , ParentCategoryId = 42},
                new BaseModel{ Id = 47, Name = "ساعت هوشمند" , ParentCategoryId = 0},
                new BaseModel{ Id = 48, Name = "هدفون" , ParentCategoryId = 41},
                new BaseModel{ Id = 49, Name = "کارت گرافیک" , ParentCategoryId = 0},
                new BaseModel{ Id = 50, Name = "اسپیکر" , ParentCategoryId = 0},
                new BaseModel{ Id = 51, Name = "رم کامپیوتر و لپ‌تاپ (RAM)" , ParentCategoryId = 0},
                new BaseModel{ Id = 52, Name = "مادربرد" , ParentCategoryId = 0},
                new BaseModel{ Id = 53, Name = "مودم" , ParentCategoryId = 0},
                new BaseModel{ Id = 54, Name = "شارژر تبلت و موبایل" , ParentCategoryId = 41},
                new BaseModel{ Id = 55, Name = "سری گالاکسی اس" , ParentCategoryId = 22},
                new BaseModel{ Id = 56, Name = "سری گالاکسی ای" , ParentCategoryId = 22},
                new BaseModel{ Id = 57, Name = "سری گالاکسی اف" , ParentCategoryId = 22},
                new BaseModel{ Id = 58, Name = "لوازم  برقی کوچک" , ParentCategoryId = 0},
                new BaseModel{ Id = 59, Name = "پخت و پز" , ParentCategoryId = 58},
                new BaseModel{ Id = 60, Name = "پلوپز" , ParentCategoryId = 59},
                new BaseModel{ Id = 61, Name = "ماکروویو" , ParentCategoryId = 59},
                new BaseModel{ Id = 62, Name = "سرمایشی" , ParentCategoryId = 58},
                new BaseModel{ Id = 63, Name = "پنکه" , ParentCategoryId = 62},
                new BaseModel{ Id = 64, Name = "مراقبت از البسه" , ParentCategoryId = 58},
                new BaseModel{ Id = 65, Name = "اتو و پایه اتو" , ParentCategoryId = 64},
                new BaseModel{ Id = 66, Name = "اتوپرس" , ParentCategoryId = 64},
                new BaseModel{ Id = 67, Name = "لوازم شخصی برقی" , ParentCategoryId = 58},
                new BaseModel{ Id = 68, Name = "اتو مو" , ParentCategoryId = 67},
                new BaseModel{ Id = 69, Name = "بند انداز برق" , ParentCategoryId = 67},
                new BaseModel{ Id = 70, Name = "حالت دهنده مو" , ParentCategoryId = 67},
                new BaseModel{ Id = 71, Name = "سشوار" , ParentCategoryId = 67},
                new BaseModel{ Id = 72, Name = "ریش تراش" , ParentCategoryId = 67},
                new BaseModel{ Id = 73, Name = "لوازم اماده سازی غذا" , ParentCategoryId = 58},
                new BaseModel{ Id = 74, Name = "آسیاب برق" , ParentCategoryId = 73},
                new BaseModel{ Id = 75, Name = "چرخ گوشت" , ParentCategoryId = 73},
                new BaseModel{ Id = 76, Name = "خردکن" , ParentCategoryId = 73},
                new BaseModel{ Id = 77, Name = "گوشت کوب برق" , ParentCategoryId = 73},
                new BaseModel{ Id = 78, Name = "مخلوط کن" , ParentCategoryId = 73},
                new BaseModel{ Id = 79, Name = "همزن برق" , ParentCategoryId = 73},
                new BaseModel{ Id = 80, Name = "همزن کاسه دار" , ParentCategoryId = 73},
                new BaseModel{ Id = 81, Name = "غذاساز" , ParentCategoryId = 73},
                new BaseModel{ Id = 82, Name = "مراقبت از سطوح" , ParentCategoryId = 58},
                new BaseModel{ Id = 83, Name = "جارو شارژی" , ParentCategoryId = 82},
                new BaseModel{ Id = 84, Name = "جاروبرقی" , ParentCategoryId = 82},
                new BaseModel{ Id = 85, Name = "آماده سازی نوشیدنی" , ParentCategoryId = 58},
                new BaseModel{ Id = 86, Name = "آبمیوه گیری" , ParentCategoryId = 85},
                new BaseModel{ Id = 87, Name = "چای ساز" , ParentCategoryId = 85},
                new BaseModel{ Id = 88, Name = "کتری و سماور برق" , ParentCategoryId = 85},
                new BaseModel{ Id = 89, Name = "اسپرسو ساز" , ParentCategoryId = 85},
                new BaseModel{ Id = 90, Name = "صوتی و تصویری" , ParentCategoryId = 0},
                new BaseModel{ Id = 91, Name = " ال ای دی 40 اینچ به پائین" , ParentCategoryId = 92},
                new BaseModel{ Id = 92, Name = "تلویزیون" , ParentCategoryId = 90},
                new BaseModel{ Id = 93, Name = " ال ای دی 41-50 اینچ" , ParentCategoryId = 92},
                new BaseModel{ Id = 94, Name = " اسمارت 41-50 اینچ" , ParentCategoryId = 92},
                new BaseModel{ Id = 95, Name = " یو اچ دی 41-50 اینچ" , ParentCategoryId = 92},
                new BaseModel{ Id = 96, Name = " اسمارت  50 اینچ به بالا" , ParentCategoryId = 92},
                new BaseModel{ Id = 97, Name = " یو اچ دی 50 اینچ به بالا" , ParentCategoryId = 92},
                new BaseModel{ Id = 98, Name = " پخش کننده صدا" , ParentCategoryId = 90},
                new BaseModel{ Id = 99, Name = "ساند بار" , ParentCategoryId = 98},
                new BaseModel{ Id = 100, Name = "کالای خواب" , ParentCategoryId = 0},
                new BaseModel{ Id = 101, Name = "پتو و لحاف" , ParentCategoryId = 100},
                new BaseModel{ Id = 102, Name = "پتو تکنفره" , ParentCategoryId = 101},
                new BaseModel{ Id = 103, Name = "لحاف دونفره" , ParentCategoryId = 101},
                new BaseModel{ Id = 104, Name = "پتو دونفره" , ParentCategoryId = 101},
                new BaseModel{ Id = 105, Name = "لحاف تکنفره" , ParentCategoryId = 101},
                new BaseModel{ Id = 106, Name = "بالش" , ParentCategoryId = 100},
                new BaseModel{ Id = 107, Name = "بالش پر" , ParentCategoryId = 106},
                new BaseModel{ Id = 108, Name = "بالش پلی استری" , ParentCategoryId = 106},
                new BaseModel{ Id = 109, Name = "بالش طبی" , ParentCategoryId = 106},
                new BaseModel{ Id = 110, Name = "تشک" , ParentCategoryId = 100},
                new BaseModel{ Id = 111, Name = "تشک عرض 90" , ParentCategoryId = 110},
                new BaseModel{ Id = 112, Name = "تشک عرض ۱۲۰" , ParentCategoryId = 110},
                new BaseModel{ Id = 113, Name = "تشک عرض 160" , ParentCategoryId = 110},
                new BaseModel{ Id = 114, Name = "تشک عرض 180" , ParentCategoryId = 110},
                new BaseModel{ Id = 115, Name = "کالای دیجیتال" , ParentCategoryId = 0},
                new BaseModel{ Id = 116, Name = "کنسول و تجهیزات بازی" , ParentCategoryId = 115},
                new BaseModel{ Id = 117, Name = " پلی استیشن" , ParentCategoryId = 116},
                new BaseModel{ Id = 118, Name = "کالای دکوری و لوکس" , ParentCategoryId = 0},
                new BaseModel{ Id = 119, Name = "روشنایی" , ParentCategoryId = 118},
                new BaseModel{ Id = 120, Name = "چراغ خواب وآباژور" , ParentCategoryId = 119},
                new BaseModel{ Id = 121, Name = "لوستر " , ParentCategoryId = 119},
                new BaseModel{ Id = 122, Name = "لوازم آشپزخانه" , ParentCategoryId = 0},
                new BaseModel{ Id = 123, Name = " لوازم پخت و پز" , ParentCategoryId = 122},
                new BaseModel{ Id = 124, Name = "ست قابلمه" , ParentCategoryId = 123},
                new BaseModel{ Id = 125, Name = " لوازم برقی بزرگ" , ParentCategoryId = 0},
                new BaseModel{ Id = 126, Name = "برودتی" , ParentCategoryId = 125},
                new BaseModel{ Id = 127, Name = "ساید بای ساید" , ParentCategoryId = 126},
                new BaseModel{ Id = 128, Name = "یخچال فریزر بالا" , ParentCategoryId = 126},
                new BaseModel{ Id = 129, Name = "یخچال فریزر " , ParentCategoryId = 126},
                new BaseModel{ Id = 130, Name = "اجاق گاز و فر" , ParentCategoryId = 125},
                new BaseModel{ Id = 131, Name = "اجاق گاز فردار" , ParentCategoryId = 130},
                new BaseModel{ Id = 132, Name = "شستوشو و نظافت" , ParentCategoryId = 125},
                new BaseModel{ Id = 133, Name = "ماشین ظرفشوئی" , ParentCategoryId = 132},
                new BaseModel{ Id = 134, Name = "ماشین لباسشوئی" , ParentCategoryId = 132},
                new BaseModel{ Id = 135, Name = " برقی تو کار" , ParentCategoryId = 125},
                new BaseModel{ Id = 136, Name = "اجاق گاز صفحه ای-هاب" , ParentCategoryId = 135},
                new BaseModel{ Id = 137, Name = "فرش و تابلو فرش" , ParentCategoryId = 0},
                new BaseModel{ Id = 138, Name = " فرش ماشینی" , ParentCategoryId = 137},
                new BaseModel{ Id = 139, Name = "فرش ماشینی تا 4 متر" , ParentCategoryId = 138},
                new BaseModel{ Id = 140, Name = "فرش ماشینی تا ۶ متر" , ParentCategoryId = 138},
                new BaseModel{ Id = 141, Name = "یخچال فریزر تک درب" , ParentCategoryId = 126},
                new BaseModel{ Id = 142, Name = "یخچال فریزر تک درب" , ParentCategoryId = 126},
                new BaseModel{ Id = 143, Name = " یخچال فریزر پایین" , ParentCategoryId = 126},
                new BaseModel{ Id = 144, Name = " مینی بار" , ParentCategoryId = 126},
                new BaseModel{ Id = 145, Name = " مینی بار" , ParentCategoryId = 126},
                new BaseModel{ Id = 146, Name = "کولر گازی" , ParentCategoryId = 126},
            };
        }
    }
}
